"""Norway company enrichment POC."""

from .identity_engine import (
    DomainMatch,
    DomainMatchCategory,
    GroupRelationship,
    GroupRelationType,
    IdentityConfidence,
    IdentityEvidence,
    IdentityVerdict,
    IdentityVerdictStatus,
    LegalNameMatch,
    LegalNameMatchCategory,
    OrgNumberValidation,
    assess_company_identity,
    canonicalize_org_number,
    classify_group_relationship,
    compute_mod11_check_digit,
    detect_ambiguity,
    extract_legal_form,
    is_valid_org_mod11,
    match_domain_entity,
    match_legal_names,
    normalize_legal_name,
    validate_org_number,
)
from .website_discovery import (
    CandidateScore,
    DiscoveryVerdictStatus,
    FetchResult,
    RequestBudget,
    SafeHttpFetcher,
    SearchCandidate,
    VerificationEvidenceLevel,
    VerificationItem,
    WebsiteDiscoveryResult,
    discover_company_website,
    discover_search_candidates,
    discover_sitemap_urls,
    parse_sitemap_xml,
    score_candidate,
    verify_exact_entity,
)
from .profile_extraction import (
    ExtractedCompanyProfile,
    ExtractedField,
    FieldStatus,
    extract_careers,
    extract_company_profile,
    extract_contact,
    extract_description,
    extract_employees,
    extract_industry,
    extract_leadership,
    extract_locations,
    extract_news,
)
from .financial_intelligence import (
    CompanyFinancialProfile,
    FinancialAccountType,
    FinancialPdfDocument,
    FinancialReportingPeriod,
    FinancialStatement,
    build_company_financial_profile,
    extract_financial_pdfs,
    extract_financials_from_pdf,
    extract_official_accounts,
)
from .evidence_engine import (
    EvidenceSelector,
    ExtractionMethod,
    ProvenanceClaim,
    SelectorType,
    SourceAuthority,
    ValidationStatus,
    ValidationVerdict,
    build_provenance_claim,
    classify_source_authority,
    compute_content_hash,
    explain_authority_rank,
    is_more_authoritative,
    validate_claim_evidence,
    verify_snapshot_match,
)
from .external_research import (
    CandidateType,
    ExternalFootprintCategory,
    ExternalFootprintItem,
    ExternalFootprintProfile,
    LeadershipEntity,
    LeadershipRoleType,
    ResearchCandidate,
    SourcePolicyDecision,
    SourcePolicyStatus,
    build_external_footprint,
    classify_leadership_role,
    discover_leadership,
    evaluate_source_policy,
    generate_research_candidates,
    normalize_domain_for_research,
    normalize_url_for_research,
)
from .change_intelligence import (
    ChangeType,
    CompanySnapshot,
    MaterialChangeRecord,
    MemorySnapshotStore,
    RefreshResult,
    RefreshStatus,
    SnapshotClaim,
    compare_snapshots,
    generate_stable_claim_key,
    is_material_change,
    normalize_semantic_value,
    refresh_company_intelligence,
)


